<?php
$this->headScript()->appendFile($this->baseUrl . 'scripts/gridsearch.js');
$grid = $this->grid;
?>
<h3>Tenedores</h3>
<p><?=$this->actionLink('Nuevo tenedor', 'tenedor','edit') ?></p>
<? if ($grid['dofilter'] == 'false' && count((array)$grid['aData']) == 0 ): ?>
	<p class="message">(no se han cargado tenedores)</p>
<? else: ?>
	<table class="grid" id="tbl_tenedor">
		<thead>
			<tr>
				<th>
					<span class="<?=$grid['tenedor_nombres_className']?>">
						<a href="#" onclick="setFormValue('tenedor:tenedor_nombres', 'grid::order', false);setFormValue('<?=$grid['tenedor_nombres_sense']?>', 'grid::sense', true);">Nombres</a>
					</span>
				</th>
				<th>
					<span class="<?=$grid['tenedor_apellido_className']?>">
						<a href="#" onclick="setFormValue('tenedor:tenedor_apellido', 'grid::order', false);setFormValue('<?=$grid['tenedor_apellido_sense']?>', 'grid::sense', true);">Apellido</a>
					</span>
				</th>
				<th>
					<span class="<?=$grid['provincia_descripcion_className']?>">
						<a href="#" onclick="setFormValue('provincia:provincia_descripcion', 'grid::order', false);setFormValue('<?=$grid['provincia_descripcion_sense']?>', 'grid::sense', true);">Provincia</a>
					</span>
				</th>
				<th>
					Colecciones
				</th>
				<th>Acciones</th>
			</tr>
			<tr id="search_params" class="search_params">
				<td>
					<input type="text" name="search_tenedor:tenedor_nombres" id="search_tenedor:tenedor_nombres" value="<?=$this->escape($grid['tenedor_nombres_searchKey'])?>">
				</td>
				<td>
					<input type="text" name="search_tenedor:tenedor_apellido" id="search_tenedor:tenedor_apellido" value="<?=$this->escape($grid['tenedor_apellido_searchKey'])?>">
				</td>
				<td>
					<select name="search_provincia:provincia_id" id="search_provincia:provincia_id">
						<option></option>
	   					<? foreach ($this->provincias as $value=>$label): ?>
	   						<? $selected = ( $value == $grid['provincia_id_searchKey']) ? 'selected="selected"' : ''; ?>
	   						<option value="<?=$value?>" <?=$selected ?>><?=$label?></option>
	   					<? endforeach; ?>
					</select>
				</td>
				<td>
					<select name="search_coleccion:coleccion_id" id="search_coleccion:coleccion_id">
						<option></option>
	   					<? foreach ($this->colecciones as $value=>$label): ?>
	   						<? $selected = ( $value == $grid['coleccion_id_searchKey']) ? 'selected="selected"' : ''; ?>
	   						<option value="<?=$value?>" <?=$selected ?>><?=$label?></option>
	   					<? endforeach; ?>
					</select>
				</td>
				<td class="actions">
					<div>
					<a href="#" class="filter" onclick="gridSearch('search_params','grid');return false;">Filtrar</a>
					<a href="#" class="unfilter" onclick="gridNoSearch('search_params','grid');return false;">Quitar Filtro</a>
					</div>
				</td>
			</tr>
		</thead>
		<tbody>
		<? $odd = true; ?>
		<? foreach ((array)$grid['aData'] as $row): ?>
			<tr class="<?=($odd)?'odd':'even' ?>">
			<? $odd = !$odd; ?>
				<td><?=$this->escape($row['tenedor_nombres'])?></td>
				<td><?=$this->escape($row['tenedor_apellido']) ?></td>
				<td><?=$this->escape($row['provincia_descripcion'])?></td>
				<td><?=$this->escape($row['tenedor_colecciones'])?></td>
				<td class="actions">
					<div>
					<?=$this->actionLink('Ver', 
						'tenedor','view',
						array('id' => $row['tenedor_id']), array('class'=>'view'),
						true, array('class'=>'view disabled'))?>	
					<?=$this->actionLink('Editar', 
						'tenedor','edit',
						array('id' => $row['tenedor_id']), array('class'=>'edit'),
						true, array('class'=>'edit disabled')) ?>
					<?=$this->actionLink('Eliminar', 
						'tenedor','delete',
						array('id' => $row['tenedor_id']), array('onclick' =>'if(confirmDelete()){return true}else{return false}', 'class' => 'delete'),
						true, array('class'=>'delete disabled')) ?>
					</div>
				</td>
			</tr>
		<? endforeach; ?>
		</tbody>
	</table>
<? endif; ?>
<?=$this->dataGridPager('grid') ?>
<?=$this->dataGridSubmit() ?>

