<table cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<p>
				<span>Usuario:</span>
				<strong><?=$this->usuario->nombre.' '.$this->usuario->apellido?></strong>
			</p>
			<p>
				<span>Rol:</span>
				<strong><?=$this->rol?></strong>
			</p>
			<p>
				<?=$this->actionLink('Salir', 'index','logout',
					array(), array('class'=>'logout'))?>
			</p>
		</td>
		<? if ($this->fotografia->id): ?>
		<td>
			<img src="<?=$this->baseUrl.'/'.$this->img_folder.'/'.$this->fotografia->nombre_archivo?>"  />
		</td>
		<? endif; ?>
	</tr>
</table>
			
