<?$id = $this->element->getElement('id');?>
<?$sigla = $this->element->getElement('sigla');?>
<?$nombre = $this->element->getElement('nombre');?>
<?$sitio_arqueologico = $this->element->getElement('sitio_arqueologico');?>
<?$observaciones = $this->element->getElement('observaciones');?>
<?$paises_all = $this->element->getElement('paises_all');?>
<?$paises_selected = $this->element->getElement('paises_selected');?>
<?$paises = $this->element->getElement('paises');?>
<?$provincia_id = $this->element->getElement('provincia_id');?>
<?$hidden_provincia_id = $this->element->getElement('hidden_provincia_id');?>
<?$departamento_id = $this->element->getElement('departamento_id');?>
<?$hidden_departamento_id = $this->element->getElement('hidden_departamento_id');?>
<?$localidad_id = $this->element->getElement('localidad_id');?>
<?$hidden_localidad_id = $this->element->getElement('hidden_localidad_id');?>
<?$tenedor_id = $this->element->getElement('tenedor_id');?>
<?$deposito_id = $this->element->getElement('deposito_id');?>
<?$deposito_temporario = $this->element->getElement('deposito_temporario'); ?>
<?$provisorio = $this->element->getElement('provisorio');?>
<?$fur = $this->element->getElement('fur');?>
<?$tipos_material_all = $this->element->getElement('tipos_material_all');?>
<?$tipos_material_selected = $this->element->getElement('tipos_material_selected');?>
<?$tipos_material = $this->element->getElement('tipos_material');?>
<?$completado_por = $this->element->getElement('completado_por');?>
<?$tipo_doc_completador_id = $this->element->getElement('tipo_doc_completador_id');?>
<?$completador_nro_doc = $this->element->getElement('completador_nro_doc');?>
<?$fecha = $this->element->getElement('fecha');?>
<?$submit = $this->element->getElement('submit');?>

<?$view = $this->element->getView();?>

<form id="<?=$this->element->getAttrib('id')?>" enctype="application/x-www-form-urlencoded" method="post" action="">
	<?=$id->render()?>
	<fieldset>
		<legend>1 - Identificación de la Colección</legend>
		<table>
			<tr>
				<th><label for="sigla"><?=$sigla->getLabel() ?></label></th>
				<td><?=$sigla->render()?></td>				
			</tr>
			<tr>
				<th><label for="nombre"><?=$nombre->getLabel() ?></label></th>
				<td><?=$nombre->render()?></td>				
			</tr>
		</table>
	</fieldset>
	
	<fieldset>
		<legend>2 - Procedencia</legend>
		<table>
			<tr>
				<th colspan="5"><label><?=$paises->getLabel() ?></label></th>
			</tr>
			<tr>
				<td colspan="5">
					<table class="multiselect">
						<tr>
							<td>
								<label for="paises_all"><?=$paises_all->getLabel() ?></label><br />
								<?=$paises_all->render()?>
							</td>
							<td style="text-align: center; vertical-align: middle">
								<input type="button" id="btn_select_pais" value="&rarr;" />
								<br /><br />
								<input type="button" id="btn_unselect_pais" value="&larr;"/>
							</td>
							<td>
								<label for="paises_selected"><?=$paises_selected->getLabel() ?></label><br />
								<?=$paises_selected->render()?><?=$paises->render()?>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<th><label for="provincia_id"><?=$provincia_id->getLabel() ?></label></th>
				<td><?=$provincia_id->render()?><?=$hidden_provincia_id->render()?></td>
				<td class="fill_column">&nbsp;</td>
				<th><label for="departamento_id"><?=$departamento_id->getLabel() ?></label></th>
				<td><?=$departamento_id->render()?><?=$hidden_departamento_id->render()?></td>
			</tr>
			<tr>
				<th><label for="localidad_id"><?=$localidad_id->getLabel() ?></label></th>
				<td><?=$localidad_id->render()?><?=$hidden_localidad_id->render()?></td>
				<td>&nbsp;</td>
				<th><label for="sitio_arqueologico"><?=$sitio_arqueologico->getLabel() ?></label></th>
				<td><?=$sitio_arqueologico->render()?></td>
			</tr>
		</table>
	</fieldset>
	
	<fieldset>
		<legend>3 - Naturaleza de la Colección</legend>
		<table>
			<tr>
				<th>Cantidad de Objetos</th>
				<td>Piezas:<?=$view->countChildObjeto?> / 
					Lotes: <?=$view->countChildLote?> 
					(<?=$view->sumChildLoteCantidadObjetos?>)</td>
				<td rowspan="3">&nbsp;</td>
				<th><label for="observaciones"><?=$observaciones->getLabel() ?></label></th>
			</tr>
			<tr>
				<td colspan="2"><?=$provisorio->render()?><label for="provisorio"><?=$provisorio->getLabel() ?></label></td>
				<td rowspan="2"><?=$observaciones->render()?></td>
			</tr>
			<tr>
				<td colspan="2"><?=$fur->render()?><label for="fur"><?=$fur->getLabel() ?></label></td>
			</tr>
			<tr>
				<th colspan="4"><label><?=$tipos_material->getLabel() ?></label></th>
			</tr>
			<tr>
				<td colspan="4">
					<table class="multiselect">
						<tr>
							<td>
								<label for="tipos_material_all"><?=$tipos_material_all->getLabel() ?></label><br />
								<?=$tipos_material_all->render()?>
							</td>
							<td style="text-align: center; vertical-align: middle">
								<input type="button" id="btn_select_tipo_material" value="&rarr;" />
								<br /><br />
								<input type="button" id="btn_unselect_tipo_material" value="&larr;"/>
								<?=$tipos_material->render()?>
							</td>
							<td>
								<label for="tipos_material_selected"><?=$tipos_material_selected->getLabel() ?></label><br />
								<?=$tipos_material_selected->render()?>		    
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
	</fieldset>
	
	<fieldset>
		<legend>4 - Datos del tenedor</legend>
		<table>
			<tr>
				<th><label for="tenedor_id"><?=$tenedor_id->getLabel() ?></label></th>
				<td><?=$tenedor_id->render()?></td>
			</tr>
		</table>
		<div id="tenedor_container">
		</div>
	</fieldset>
	
	<fieldset>
		<legend>5 - Lugar de Depósito</legend>
		<table>
			<tr>
				<th><label for="deposito_id"><?=$deposito_id->getLabel() ?></label></th>
				<td><?=$deposito_id->render()?></td>
			</tr>
			<tr>
				<th><label for="deposito_temporario"><?=$deposito_temporario->getLabel() ?></label></th>
				<td><?=$deposito_temporario->render()?></td>
			</tr>
		</table>
		<div id="deposito_container">
		</div>
	</fieldset>
		
	<fieldset>
		<legend>Datos de la ficha</legend>
		<table>
		  <tr>
        <th><label for="tipo_doc_completador_id"><?=$tipo_doc_completador_id->getLabel() ?></label></th>
        <td><?=$tipo_doc_completador_id->render()?></td>
        <td class="fill_column">&nbsp;</td>
        <th><label for="completador_nro_doc"><?=$completador_nro_doc->getLabel() ?></label></th>
        <td><?=$completador_nro_doc->render()?></td>
      </tr>
			<tr>
				<th><label for="completado_por"><?=$completado_por->getLabel() ?></label></th>
				<td><?=$completado_por->render()?></td>
				<td class="fill_column">&nbsp;</td>
				<th><label for="fecha"><?=$fecha->getLabel() ?></label></th>
				<td><?=$fecha->render()?></td>
			</tr>
		</table>
	</fieldset>
	
	
	<p class="actions">
		<?=$submit->render()?>
	</p>
</form>