<?php
$this->headScript()->appendFile($this->baseUrl . 'scripts/jquery.pngfix.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/jquery.fancybox.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/lote_view.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/iframe_resize.js');
$this->headLink()->appendStylesheet($this->baseUrl . 'styles/fancy.css');
?>
<h3>Lote - Detalle</h3>
<p>
<?=$this->actionLink('&lt;&lt; Volver al listado', 'lote', 'index', array(), array('class'=>'back')) ?>
<br style="clear:both" />
</p>
<h4>1 - Identificación del Lote</h4>
<dl class="view">
	<dt>Colección:</dt>
	<dd><?=Coleccion::findByPK($this->lote->coleccion_id)?>&nbsp;</dd> 
	
	<dt>Sigla:</dt>
	<dd><?=$this->escape($this->lote->sigla)?>&nbsp;</dd> 
	
	<dt>Tipo de Material:</dt>
	<dd><?=TipoMaterial::findByPK($this->lote->tipo_material_id)?>&nbsp;</dd>
	
	<dt>Nombre:</dt>
	<dd><?=$this->escape($this->lote->nombre)?>&nbsp;</dd>  
</dl>
<h4>2 - Localización</h4>
<dl class="view">	
	<dt>País:</dt>
	<dd><?=Pais::findByPK($this->lote->pais_id)?>&nbsp;</dd> 
	
	<? if ($this->lote->pais_id == 1): ?>
	
		<dt>Provincia:</dt>
		<dd><?=Provincia::findByPK($this->lote->provincia_id)?>&nbsp;</dd> 
		
		<dt>Departamento:</dt>
		<dd><?=Departamento::findByPK($this->lote->departamento_id)?>&nbsp;</dd> 
		
		<dt>Localidad:</dt>
		<dd><?=Localidad::findByPK($this->lote->localidad_id)?>&nbsp;</dd> 

  <? else: ?>
  
    <dt>Detalle:</dt>
    <dd><?=$this->lote->pais_detalle?>&nbsp;</dd>
    
  <? endif; ?>
  
	<dt>Sitio arqueológico:</dt>
	<dd><?=$this->escape(Yacimiento::findByPK($this->lote->yacimiento_id))?>&nbsp;</dd> 
</dl>
<h4>3 - Descripción del Lote</h4>
<dl class="view">	
	<dt>Descripción del lote:</dt>
	<dd><?=$this->escape($this->lote->descripcion)?>&nbsp;</dd>
	
	<dt>Cantidad de Objetos:</dt>
	<dd><?=$this->lote->cantidad_objetos?>&nbsp;</dd> 
</dl>
<h4>4 - Datos del tenedor</h4>
<dl class="view">	
	<dt>&nbsp;</dt>
	<dd>
		<input type="hidden" id="coleccion_id" value="<?=$this->lote->coleccion_id?>" />
		<div id="tenedor_container" class="view"></div>&nbsp;
	</dd>
</dl>
<div class="noprint">
<h4>5 - Fotografías</h4>
<iframe src="<?=$this->url('fotografia','index',array('lote_id'=>$this->lote->id, 'mode'=>'view'),Zend_Registry::get('config')->base_url)?>" 
			scrolling="no" marginwidth="0" marginheight="0" frameborder="0" vspace="0" hspace="0" style="overflow:visible; width:100%"></iframe>
</div>
<h4>6 - Adscripciones Culturales</h4>
<dl class="view">	
	<dt>&nbsp;</dt>
	<dd>
		<ul>
		<? foreach ($this->adscripciones_culturales as $adscripcion_cultural): ?>
			<li><?= $adscripcion_cultural ?></li>
		<? endforeach; ?>
		</ul>&nbsp;
	</dd>
</dl>
<h4>Datos de la ficha</h4>		 
<dl class="view">
	<dt>Completado por:</dt>
	<dd><?=$this->escape($this->lote->completado_por)?>&nbsp;</dd> 
	
	<dt>Fecha:</dt>
	<dd><?=$this->lote->fecha?>&nbsp;</dd>
</dl>
<div class="actions">
<a href="#" onclick="window.open('<?=$this->url('lote','view',array('id' => $this->lote->id, 'print'=>true))?>','','height=720,width=960,scrollbars=yes')" class="print">Imprimir</a>
<?=$this->actionLink('Editar', 
	'lote','edit',
	array('id' => $this->lote->id), array('class'=>'edit'),
	true, array('class'=>'edit disabled')) ?>
<?=$this->actionLink('Eliminar', 
	'lote','delete',
	array('id' => $this->lote->id), array('onclick' =>'if(confirmDelete()){return true}else{return false}', 'class' => 'delete'),
	true, array('class'=>'delete disabled')) ?>
</div>
<br style="clear: both"/>