<?php
$this->headScript()->appendFile($this->baseUrl . 'scripts/gridsearch.js');
$grid = $this->grid;
?>
<h3>Yacimientos</h3>
<p><?=$this->actionLink('Nuevo yacimiento', 'yacimiento','edit') ?></p>
<? if ($grid['dofilter'] == 'false' && count((array)$grid['aData']) == 0 ): ?>
	<p class="message">(no se han cargado yacimientos)</p>
<? else: ?>
	<table class="grid" id="tbl_yacimiento">
		<thead>
			<tr>
				<th>
					<span class="<?=$grid['yacimiento_denominacion_sitio_className']?>">
						<a href="#" onclick="setFormValue('yacimiento:yacimiento_denominacion_sitio', 'grid::order', false);setFormValue('<?=$grid['yacimiento_denominacion_sitio_sense']?>', 'grid::sense', true);">Denominación Sitio</a>
					</span>
				</th>
				<th>
					<span class="<?=$grid['provincia_descripcion_className']?>">
						<a href="#" onclick="setFormValue('provincia:provincia_descripcion', 'grid::order', false);setFormValue('<?=$grid['provincia_descripcion_sense']?>', 'grid::sense', true);">Provincia</a>
					</span>
				</th>
				<th>
					Adsc. Culturales
				</th>
				<th>Acciones</th>
			</tr>
			<tr id="search_params" class="search_params">
				<td>
					<input type="text" name="search_yacimiento:yacimiento_denominacion_sitio" id="search_yacimiento:yacimiento_denominacion_sitio" value="<?=$this->escape($grid['yacimiento_denominacion_sitio_searchKey'])?>">
				</td>
				<td>
					<select name="search_provincia:provincia_id" id="search_provincia:provincia_id">
						<option></option>
	   					<? foreach ($this->provincias as $value=>$label): ?>
	   						<? $selected = ( $value == $grid['provincia_id_searchKey']) ? 'selected="selected"' : ''; ?>
	   						<option value="<?=$value?>" <?=$selected ?>><?=$label?></option>
	   					<? endforeach; ?>
					</select>
				</td>
				<td>
					<select name="search_adscripcion_cultural:adscripcioncultural_id" id="search_adscripcion_cultural:adscripcioncultural_id">
						<option></option>
	   					<? foreach ($this->adscripcionesculturales as $value=>$label): ?>
	   						<? $selected = ( $value == $grid['adscripcioncultural_id_searchKey']) ? 'selected="selected"' : ''; ?>
	   						<option value="<?=$value?>" <?=$selected ?>><?=$label?></option>
	   					<? endforeach; ?>
					</select>
				</td>
				<td class="actions">
					<div>
						<a href="#" class="filter" onclick="gridSearch('search_params','grid');return false;">Filtrar</a>
						<a href="#" class="unfilter" onclick="gridNoSearch('search_params','grid');return false;">Quitar Filtro</a>
					</div>
				</td>
			</tr>
		</thead>
		<tbody>
		<? $odd = true; ?>
		<? foreach ((array)$grid['aData'] as $row): ?>
			<tr class="<?=($odd)?'odd':'even' ?>">
			<? $odd = !$odd; ?>
				<td><?=$this->escape($row['yacimiento_denominacion_sitio']) ?></td>
				<td><?=$this->escape($row['provincia_descripcion'])?></td>
				<td><?=$this->escape($row['yacimiento_adscripciones_culturales'])?></td>
				<td class="actions">
					<div>
					<?=$this->actionLink('Ver', 
						'yacimiento','view',
						array('id' => $row['yacimiento_id']), array('class'=>'view'),
						true, array('class'=>'view disabled'))?>		
					<?=$this->actionLink('Editar', 
						'yacimiento','edit',
						array('id' => $row['yacimiento_id']), array('class'=>'edit'),
						true, array('class'=>'edit disabled')) ?>
					<?=$this->actionLink('Eliminar', 
						'yacimiento','delete',
						array('id' => $row['yacimiento_id']), array('onclick' =>'if(confirmDelete()){return true}else{return false}', 'class' => 'delete'),
						true, array('class'=>'delete disabled')) ?>
					</div>
				</td>
			</tr>
		<? endforeach; ?>
		</tbody>
	</table>
<? endif; ?>
<?=$this->dataGridPager('grid') ?>
<?=$this->dataGridSubmit() ?>
<p><?=$this->actionLink('Generar Reporte', 'yacimiento','report') ?></p>
