<?php
$this->headScript()->appendFile($this->baseUrl . 'scripts/datepicker/datepicker.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/datepicker/i18n/ui.datepicker-es.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/coleccion_edit.js');
$this->headScript()->appendFile($this->baseUrl . 'scripts/multiselect.js');
$this->headLink()->appendStylesheet($this->baseUrl . 'styles/datepicker.css');
?>
<h3>Colección - Edición</h3>  
<p>
<?=$this->actionLink('&lt;&lt; Volver al listado', 'coleccion','index', array(), array('class'=>'back')) ?>
<br style="clear:both" />
</p>
<?= $this->form; ?> 
